### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by mibmo** [ThomasCX/defragfs#6]
Any chance of getting a license in the repo? Preferably something like MIT? ;)

I'm packaging this for [nixpkgs](https://github.com/nixos/nixpkgs) and need to set a license.

**Comment by ThomasCX** [comment]
Hi,

You can assume the MIT license :)

Thomas

**Comment by mibmo** [comment]
Alright, that's fair! :) I'll just link to this issue.
If I make a PR to add the MIT license though, would you merge it? Just to keep it simple :)

Thanks for the response nonetheless!

**Comment by ThomasCX** [comment]
Sure, no problem.

**Comment by mibmo** [comment]
Resolved by #7
